# Generated by Django 4.2.1 on 2023-12-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password1', models.CharField(auto_created='NAsbK41j', max_length=8, verbose_name='Пароль')),
                ('login1', models.CharField(auto_created='aNdRLUqk', max_length=8, verbose_name='Логин')),
                ('name_student', models.CharField(max_length=100, verbose_name='ФИО')),
                ('number_class', models.IntegerField(verbose_name='Номер класса')),
                ('word_class', models.CharField(max_length=10, verbose_name='Буква класса')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_tasks', models.IntegerField(verbose_name='Номер в ЕГЭ')),
                ('image_tasks', models.CharField(max_length=100, verbose_name='Картинка')),
                ('otvet_tasks', models.CharField(max_length=100, verbose_name='Правильный отет')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
    ]
