# Generated by Django 4.2.1 on 2023-11-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_student', models.CharField(max_length=100, verbose_name='ФИО')),
                ('date_student', models.DateField(verbose_name='Дата рождения')),
                ('age_student', models.IntegerField(verbose_name='Возраст')),
                ('number_class', models.IntegerField(verbose_name='Номер класса')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
    ]
