# Generated by Django 4.2.1 on 2023-12-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_articles_login1_alter_articles_password1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='login1',
            field=models.CharField(default='IQQSgWsc', max_length=8, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='password1',
            field=models.CharField(default='Oo5FIddz', max_length=8, verbose_name='Пароль'),
        ),
    ]
